<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-07-15T14:52:28Z" name="Default suite" finished-at="2019-07-15T14:52:34Z" duration-ms="6135">
    <groups>
    </groups>
    <test started-at="2019-07-15T14:52:28Z" name="Default test" finished-at="2019-07-15T14:52:34Z" duration-ms="6135">
      <class name="webdriverManager.HowToUseWebdriverManager">
        <test-method is-config="true" signature="setup()[pri:0, instance:webdriverManager.HowToUseWebdriverManager@1f59a598]" started-at="2019-07-15T14:52:28Z" name="setup" finished-at="2019-07-15T14:52:34Z" duration-ms="6074" status="FAIL">
          <exception class="io.github.bonigarcia.wdm.WebDriverManagerException">
            <message>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index -5 out of bounds for length 5]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IndexOutOfBoundsException: Index -5 out of bounds for length 5
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:723)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:720)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
at webdriverManager.HowToUseWebdriverManager.setup(HowToUseWebdriverManager.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IndexOutOfBoundsException: Index -5 out of bounds for length 5
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:458)
at io.github.bonigarcia.wdm.EdgeDriverManager.getDrivers(EdgeDriverManager.java:151)
at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:739)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:534)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- io.github.bonigarcia.wdm.WebDriverManagerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="WebdriverManagerTest()[pri:0, instance:webdriverManager.HowToUseWebdriverManager@1f59a598]" started-at="2019-07-15T14:52:34Z" name="WebdriverManagerTest" finished-at="2019-07-15T14:52:34Z" duration-ms="0" status="SKIP">
          <exception class="io.github.bonigarcia.wdm.WebDriverManagerException">
            <message>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index -5 out of bounds for length 5]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IndexOutOfBoundsException: Index -5 out of bounds for length 5
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:723)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:720)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
at webdriverManager.HowToUseWebdriverManager.setup(HowToUseWebdriverManager.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IndexOutOfBoundsException: Index -5 out of bounds for length 5
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:458)
at io.github.bonigarcia.wdm.EdgeDriverManager.getDrivers(EdgeDriverManager.java:151)
at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:739)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:534)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- io.github.bonigarcia.wdm.WebDriverManagerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebdriverManagerTest -->
      </class> <!-- webdriverManager.HowToUseWebdriverManager -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
